export const CONNECTIONS_DATA = [
  {
    id: 1,
    name: "Lorem ipsum dolor sit",
    project_id: "NHJ-KLP-90897",
    cloud_provider: "AWS",
    connection_type: "Wayam",
    created_date: "02/17/2023",
    created_by: "Mike White",
    last_checked: "02/17/2023",
    last_success: "02/17/2023 - 08:15 CST",
    account_type: "Root",
    connection_status: "success",
    child_connections: [
      {
        id: 1,
        name: "Lorem ipsum dolor sit",
        project_id: "NHJ-KLP-90897",
        cloud_provider: "AWS",
        connection_type: "Wayam",
        created_date: "02/17/2023",
        created_by: "Summer Greek",
        last_checked: "02/17/2023",
        last_success: "02/17/2023 - 08:15 CST",
        account_type: "Production",
        connection_status: "success",
      },
    ],
    expand: false,
  },
  {
    id: 2,
    name: "Dolor sit amet consectetur",
    project_id: "KLP-NHJ-34512",
    cloud_provider: "GCP",
    connection_type: "Customer",
    created_date: "10/01/2023",
    created_by: "Jannel Rubben",
    last_checked: "10/01/2023",
    last_success: "02/17/2023 - 08:15 CST",
    account_type: "Payer",
    connection_status: "failed",
    child_connections: [],
    expand: false,
  },  
  {
    id: 3,
    name: "Lorem ipsum",
    project_id: "KLP-NHJ-34513",
    cloud_provider: "Azure",
    connection_type: "Partner",
    created_date: "11/05/2023",
    created_by: "Alice Johnson",
    last_checked: "11/05/2023",
    last_success: "02/20/2023 - 10:30 CST",
    account_type: "Receiver",
    connection_status: "success",
    child_connections: [],
    expand: false,
  },
  {
    id: 4,
    name: "Consectetur adipiscing",
    project_id: "KLP-NHJ-34514",
    cloud_provider: "AWS",
    connection_type: "Vendor",
    created_date: "12/10/2023",
    created_by: "Bob Smith",
    last_checked: "12/10/2023",
    last_success: "03/05/2023 - 15:45 CST",
    account_type: "Payer",
    connection_status: "success",
    child_connections: [],
    expand: false,
  },
  {
    id: 5,
    name: "Sed do eiusmod tempor",
    project_id: "KLP-NHJ-34515",
    cloud_provider: "GCP",
    connection_type: "Customer",
    created_date: "01/15/2024",
    created_by: "Charlie Brown",
    last_checked: "01/15/2024",
    last_success: "03/20/2023 - 12:00 CST",
    account_type: "Receiver",
    connection_status: "failed",
    child_connections: [],
    expand: false,
  },
  {
    id: 6,
    name: "Ut labore et dolore magna",
    project_id: "KLP-NHJ-34516",
    cloud_provider: "Azure",
    connection_type: "Partner",
    created_date: "02/20/2024",
    created_by: "David Wilson",
    last_checked: "02/20/2024",
    last_success: "04/02/2023 - 18:30 CST",
    account_type: "Payer",
    connection_status: "success",
    child_connections: [],
    expand: false,
  },
  {
    id: 7,
    name: "Adipiscing elit sed do",
    project_id: "KLP-NHJ-34517",
    cloud_provider: "AWS",
    connection_type: "Vendor",
    created_date: "03/25/2024",
    created_by: "Eva Martinez",
    last_checked: "03/25/2024",
    last_success: "04/15/2023 - 09:00 CST",
    account_type: "Receiver",
    connection_status: "failed",
    child_connections: [],
    expand: false,
  }
];
