export const CONNECTIONS_DATA = [
  {
    id: 1,
    name: "Lorem ipsum dolor sit",
    project_id: "NHJ-KLP-90897",
    cloud_provider: "AWS",
    connection_type: "Wayam",
    created_date: "02/17/2023",
    created_by: "Mike White",
    last_checked: "02/17/2023",
    last_success: "02/17/2023 - 08:15 CST",
    account_type: "Root",
    connection_status: "success",
    child_connections: [
      {
        id: 1,
        name: "Lorem ipsum dolor sit",
        project_id: "NHJ-KLP-90897",
        cloud_provider: "AWS",
        connection_type: "Wayam",
        created_date: "02/17/2023",
        created_by: "Summer Greek",
        last_checked: "02/17/2023",
        last_success: "02/17/2023 - 08:15 CST",
        account_type: "Production",
        connection_status: "success",
      },
    ],
    expand: false,
  },
  {
    id: 2,
    name: "Dolor sit amet consectetur",
    project_id: "KLP-NHJ-34512",
    cloud_provider: "GCP",
    connection_type: "Customer",
    created_date: "10/01/2023",
    created_by: "Jannel Rubben",
    last_checked: "10/01/2023",
    last_success: "02/17/2023 - 08:15 CST",
    account_type: "Payer",
    connection_status: "failed",
    child_connections: [],
    expand: false,
  },
];
