import Dashboard from "../Dashboard";
import Connections from "../Connections";
import Teams from "../Teams";
import Users from "../Users";
import Roles from "../Roles";
import Integration from "../Integration";
import Optimization from "../Optimization";

export const SIDEBAR_LIST = [
  {
    id: 1,
    icon: "home",
    title: "Dashboard",
    subtitle: [],
    path: "/dashboard",
    renderTo: Dashboard,
    expand: false,
  },
  {
    id: 2,
    icon: "estimations",
    title: "Estimations",
    subtitle: [],
    path: "/estimations",
    renderTo: Dashboard,
    expand: false,
  },
  {
    id: 3,
    icon: "forecast",
    title: "Budget & Forecast",
    subtitle: [],
    path: "/forecast",
    renderTo: Dashboard,
  },
  {
    id: 4,
    icon: "optimization",
    title: "Optimization",
    subtitle: [],
    path: "/optimization",
    renderTo: Optimization,
    expand: false,
  },
  {
    id: 5,
    icon: "policies",
    title: "Controls & Policies",
    subtitle: [],
    path: "/policies",
    renderTo: Dashboard,
    expand: false,
  },
  {
    id: 6,
    icon: "alerts",
    title: "Alerts",
    subtitle: [],
    path: "/alerts",
    renderTo: Dashboard,
    expand: false,
  },
  {
    id: 7,
    icon: "reports",
    title: "Reports",
    subtitle: [],
    path: "/reports",
    renderTo: Dashboard,
    expand: false,
  },
  {
    id: 8,
    icon: "query",
    title: "Query",
    subtitle: [],
    path: "/query",
    renderTo: Dashboard,
    expand: false,
  },
  {
    id: 9,
    icon: "setup",
    title: "Settings",
    subtitle: [
      {
        subId: 1,
        icon: "connections",
        title: "Connections",
        subtitle: [],
        path: "/connection_resource",
        renderTo: Connections,
        expand: false,
      },
      {
        subId: 2,
        icon: "users",
        title: "Users",
        subtitle: [],
        path: "/users",
        renderTo: Users,
        expand: false,
      },
      {
        subId: 3,
        icon: "teams",
        title: "Teams",
        subtitle: [],
        path: "/teams",
        renderTo: Teams,
        expand: false,
      },
      {
        subId: 4,
        icon: "roles",
        title: "Roles",
        subtitle: [],
        path: "/roles",
        renderTo: Roles,
        expand: false,
      },
      {
        subId: 5,
        icon: "integration",
        title: "Integration",
        subtitle: [],
        path: "/integration",
        renderTo: Integration,
        expand: false,
      },
    ],
    path: "/settings",
    renderTo: Dashboard,
    expand: false,
  },
  {
    id: 10,
    icon: "billing",
    title: "Billing",
    subtitle: [],
    path: "/billing",
    renderTo: Dashboard,
    expand: false,
  },
  {
    id: 11,
    icon: "support",
    title: "Support",
    subtitle: [],
    path: "/support",
    renderTo: Dashboard,
    expand: false,
  },
  {
    id: 12,
    icon: "account",
    title: "Account",
    subtitle: [],
    path: "/account",
    renderTo: Dashboard,
    expand: false,
  },
];
